### ISSUE TITLE
Las mascotas deberían ser adoptadas

### ISSUE THREAD

**Issue by demency** [Alimentalos/Backend#134]
El caso _de la negra_ sirvió para demostrar que de brindar un cuidado estructurado a una entidad esta podría ser fácilmente visibilizada y reintegrada por la comunidad. 

El caso _del rex_ sirvió para demostrar que se puede establecer un proceso para adoptar mascotas que a diferencia del caso de la negra, no poseen la fuerza suficiente para gestionar su recuperación. La negra tenía la posibilidad de relacionarse con personas hasta que encontró a la persona definitiva.

@edidk7 en base a esos datos presentados creo que los recursos producidos en:

- https://github.com/ZenDevSpA/Adoptalos/issues/2 
- https://github.com/ZenDevSpA/Adoptalos/issues/3

Deberían ser implementados en este proyecto, ya que en sus contenidos poseen características que ya están resueltas en este proyecto. ¿Qué piensas tu?

**Comment by edidk7** [comment]
@demency esta bien, pero tu dices que traiga todo el HTML y CSS  para integrarlo en una vista blade en este proyecto ?
