### ISSUE TITLE
Flujo del proceso de adopción

### ISSUE THREAD

**Issue by demency** [Alimentalos/Backend#135]
> En el caso de _rex_, una vez identificado el evento negativo de la muerte de la hermana de rex por lo que se puede evidenciar un directo ataque del mal, a continuación se toma la decisión de rescatar al sobreviviente. Para ello se le brinda una vivienda temporal y se gestiona un ofrecimiento a través de las redes sociales hasta que una familia decide quedarse con él. 

En cuanto al proceso:

1. Los elementos identificables de la mascota son recolectados (Fotografías del animal y de ser posible la de sus creadores).
2. La mascota es enviada al veterinario con el fin de verificar su estado de salud y seguir recomendaciones.
3. La mascota es entregada con documentación, un contrato y una carta de compromiso. 
4. Fotografías, comentarios y más podrían recolectarse en un futuro.

Sinceramente soy pésimo documentando procesos de modelo de negocio, recuerdo las clases de Manuel Rojas, un docente de mala calaña que se preocupaba de venderte una suit de modelado o al demonio rojo (Oracle) de todos los modos posibles en vez de enseñarte los símbolos, patrones y claves. En fín, @edidk7 crees que podrías jugar con UML y BPMN para hacer algún bosquejo de esto?

**Comment by edidk7** [comment]
@demency claro que si, diseñare unos modelos con el flujo que describiste.

**Comment by edidk7** [comment]
https://drive.google.com/file/d/16WyTSBrxjqcPVuRLFuwJ195ZZlwCEfgo/view?usp=sharing

@demency en este enlace estaran los diagramas de la solicitud de adoptar mascota.
